export const APP_ROUTES = [
  { href: "/dashboard", label: "Dashboard" },
  { href: "/processo", label: "Processo 13 Abas" },
  { href: "/projetos", label: "Projetos" },
  { href: "/projetos/elicon/cadastro", label: "Cadastro" },
  { href: "/projetos/elicon/riscos-alertas", label: "Riscos & Alertas" },
  { href: "/projetos/elicon/diario", label: "Painel Diário" },
  { href: "/projetos/elicon/conciliacao", label: "Conciliação" },
  { href: "/projetos/elicon/operacoes", label: "Operações" },
  { href: "/projetos/elicon/fluxo-caixa", label: "Fluxo 90d" },
  { href: "/projetos/elicon/dre-dfc", label: "DRE / DFC" },
  { href: "/projetos/elicon/rotina-diaria", label: "Rotina" },
  { href: "/projetos/elicon/delivery", label: "Delivery" },
  { href: "/projetos/elicon/fechamento-mensal", label: "Fechamento" },
  { href: "/auditoria-uso", label: "Auditoria" },
  { href: "/admin", label: "Admin" },
  { href: "/admin/status", label: "Status Ops" },
] as const;
